/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("hr.mmaracic.java-application-conventions")
    id("com.microsoft.azure.azurewebapp") version "1.8.0"
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-web")
}

azurewebapp {
    subscription = "53d28b9b-a7f8-4902-a2a1-559a768debdf"
    resourceGroup = "app"
    appName = "mm-webapp-be"
    pricingTier = "F1"
    region = "westeurope"
    setRuntime(closureOf<com.microsoft.azure.gradle.configuration.GradleRuntimeConfig> {
        os("Linux")
        webContainer("Java SE")
        javaVersion("Java 17")
    })
    setAppSettings(closureOf<MutableMap<String, String>> {
//        put("key", "value")
    })
    setAuth(closureOf<com.microsoft.azure.gradle.auth.GradleAuthConfig> {
        type = "azure_cli"
    })
}