/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // NOTE: external plugin version is specified in implementation dependency artifact of the project's build file
    id("io.spring.dependency-management")
    //applies spring BOM to define compatible version for spring related library
    id("java-test-fixtures")
    //produces test fixtures which are expected in folder src/testFixtures/java of the module

    // Apply the java Plugin to add support for Java.
    java
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

group "hr.mmaracic"
version "1.0-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_17

//Needs to be here otherwise versions won't transfer to modules that do not apply org.springframework.boot plugin (libraries)
dependencyManagement {
    imports {
        mavenBom(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES)
    }
}


dependencies {
    testImplementation("org.springframework.boot:spring-boot-starter-test")

    // Implementation dependencies are not leaked to consumers when building
    testFixturesImplementation("org.springframework.boot:spring-boot-starter-test")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
